# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    app.google_client_id: '%env(GOOGLE_CLIENT_ID)%'
    app.google_client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
    app.google_redirect_uri: '%env(GOOGLE_REDIRECT_URI)%'
    app.frontend_url: '%env(FRONTEND_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\DataFixtures\Purger\MysqlPurgerFactory:
        tags: [{ name: doctrine.fixtures.purger_factory, alias: mysql }]
